import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import UserBalance from '../components/UserBalance';
import { useAccount } from 'wagmi';

const Home: NextPage = () => {

  const account = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>Simple Wallet App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className='flex flex-col gap-[10px] justify-center items-center'>
          <div>
            <ConnectButton accountStatus={'address'} showBalance={false} />
          </div>
          {account.isConnected && (
            <div>
              <UserBalance />
            </div>
          )}
        </div>
        
      </main>

      <footer className={styles.footer}>
        <p className='flex flex-row gap-[5px] items-center justify-center'>
          <span>&copy; made by</span> <a target='_blank' href="https://elshadaghayev.com" className='!underline'>Elshad Aghayev</a>
        </p>
      </footer>
    </div>
  );
};

export default Home;
